import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import NavbarElm from "@/app/components/ui/layout/NavbarElm";
import Link from "next/link";
import Sidebar from "@/app/components/ui/layout/Sidebar";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        {/*<NavbarElm/>*/}
        {/*<div>{children}</div>*/}
        <div className="flex flex-col min-h-screen">
            <header className="bg-gray-800 text-white p-4">
                <nav>
                    <ul className="flex space-x-4">
                        <li>
                            <Link href="/">
                                Home
                            </Link>
                        </li>
                       {/* <li>
                            <Link href="/">
                                <a>About</a>
                            </Link>
                        </li>
                        <li>
                            <Link href="/">
                                <a>Contact</a>
                            </Link>
                        </li>*/}
                    </ul>
                </nav>
            </header>
            <Sidebar/>
            <main className="flex-grow container mx-auto py-8">{children}</main>
            <footer className="bg-gray-800 text-white p-4">
                This is the footer
            </footer>
        </div>
        </body>
        </html>
    );
}
