import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Container} from "react-bootstrap";
import NavbarElm from "@/app/components/ui/layout/NavbarElm";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={inter.className}>
        <NavbarElm/>
        <Container className={"container-md mt-8"}>{children}</Container></body>
    </html>
  );
}
