import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Sidebar from "@/app/components/ui/layout/Sidebar";


const inter = Inter({subsets: ["latin"]});
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className={"h-full bg-white"} lang="en">
        <body className={inter.className + "h-full"}>
        <Sidebar/>
        <main className="py-10 lg:pl-72">
            <div className="px-4 sm:px-6 lg:px-8">{children}</div>
        </main>
        </body>
        </html>
    );
}
